-- Drop old table and recreate with proper camelCase quoting
DROP TABLE IF EXISTS public.field_inspections;

CREATE TABLE public.field_inspections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "recordType" TEXT NOT NULL DEFAULT '',
  "mosque_name" TEXT DEFAULT '',
  "region" TEXT DEFAULT '',
  "visit_date" TEXT DEFAULT '',
  "facility_evaluations" JSONB DEFAULT '{}',
  "general_notes" TEXT DEFAULT '',
  "recommendations" TEXT DEFAULT '',
  "full_name" TEXT DEFAULT '',
  "gender" TEXT DEFAULT '',
  "age" TEXT DEFAULT '',
  "marital_status" TEXT DEFAULT '',
  "phone" TEXT DEFAULT '',
  "residence_area" TEXT DEFAULT '',
  "disability_type" TEXT DEFAULT '',
  "disability_degree" TEXT DEFAULT '',
  "disability_cause" TEXT DEFAULT '',
  "is_permanent" TEXT DEFAULT '',
  "uses_wheelchair" TEXT DEFAULT '',
  "education_level" TEXT DEFAULT '',
  "is_studying" TEXT DEFAULT '',
  "last_qualification" TEXT DEFAULT '',
  "needs" JSONB DEFAULT '[]',
  "other_needs" TEXT DEFAULT '',
  "created_at" TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.field_inspections ENABLE ROW LEVEL SECURITY;

CREATE POLICY "anon_all" ON public.field_inspections
  FOR ALL TO anon USING (true) WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_field_inspections_record_type ON public.field_inspections ("recordType");
CREATE INDEX IF NOT EXISTS idx_field_inspections_created_at ON public.field_inspections ("created_at" DESC);
