-- تشغيل هذا الملف في SQL Editor في Supabase Dashboard
-- https://supabase.com/dashboard/project/gffszrqotpzdztpltivr/sql/new

-- 1. حذف الجدول القديم (يحتوي على 3 سجلات من النسخة القديمة)
DROP TABLE IF EXISTS public.field_inspections;

-- 2. إنشاء الجدول الجديد
CREATE TABLE public.field_inspections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recordType TEXT NOT NULL,
  -- mosque fields
  mosque_name TEXT DEFAULT '',
  region TEXT DEFAULT '',
  visit_date TEXT DEFAULT '',
  facility_evaluations JSONB DEFAULT '{}',
  general_notes TEXT DEFAULT '',
  recommendations TEXT DEFAULT '',
  -- disability fields
  full_name TEXT DEFAULT '',
  gender TEXT DEFAULT '',
  age TEXT DEFAULT '',
  marital_status TEXT DEFAULT '',
  phone TEXT DEFAULT '',
  residence_area TEXT DEFAULT '',
  disability_type TEXT DEFAULT '',
  disability_degree TEXT DEFAULT '',
  disability_cause TEXT DEFAULT '',
  is_permanent TEXT DEFAULT '',
  uses_wheelchair TEXT DEFAULT '',
  education_level TEXT DEFAULT '',
  is_studying TEXT DEFAULT '',
  last_qualification TEXT DEFAULT '',
  needs JSONB DEFAULT '[]',
  other_needs TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. تفعيل Row Level Security
ALTER TABLE public.field_inspections ENABLE ROW LEVEL SECURITY;

-- 4. السماح للـ anon key بعمليات CRUD
CREATE POLICY "anon_insert" ON public.field_inspections
  FOR INSERT TO anon WITH CHECK (true);

CREATE POLICY "anon_select" ON public.field_inspections
  FOR SELECT TO anon USING (true);

CREATE POLICY "anon_update" ON public.field_inspections
  FOR UPDATE TO anon USING (true);

CREATE POLICY "anon_delete" ON public.field_inspections
  FOR DELETE TO anon USING (true);

-- 5. دعم البحث الفوري
CREATE INDEX IF NOT EXISTS idx_field_inspections_record_type ON public.field_inspections (recordType);
CREATE INDEX IF NOT EXISTS idx_field_inspections_created_at ON public.field_inspections (created_at DESC);
